### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by nhoxbypass** [quanguefa23/Anthenticator-Java-Android#1]
# Code Review

Hi  @quanguefa23 , I have after reviewing some parts of your project, I have some note for you.

## Good stuffs

- You used many trending libs/frameworks (**Retrofit, Room,..**).
- You used **Dependencies Injection** (using Dagger2). It will make it easy to maintain & be able to test.
- You used **2-ways data binding** to bind data directly into XML layouts, that's really good!
- You used **MVVM pattern** with ViewModel, LiveData from Jetpack. Your codebase organization (horizontally by layer) is good.
- You used **DiffUtil** in your RecyclerView to optimize the binding.
- You implemented our own threading solution (instead of using deprecated AsyncTask).

#### Coding

- Try rewriting the project using **Kotlin**!
- Replace normal Gradle with **Kotlin DSL**. Split lib versions into a separate file to easy to track & maintain.
- **Don't expose `MutableLiveData`** of your observable fields. Only return `LiveData`, or the usages can post events and make it harder to control the flow. (Ex: change `MutableLiveData<Boolean> getTriggerUpdateTime()` to `LiveData<Boolean> getTriggerUpdateTime()`).

#### Architecture

- Split the `SharedPreferences` data access into the data repository (instead of access directly in ViewModel). So your **ViewModel can be independent of which prefs framework you used**.
- **Abstract the login flows behind your own interface**, so your ViewModel will not be coupled with `GoogleSignIn`, and you can change it to other frameworks later.
- Hide the source of data (remote/local,..) by remove `getLocalDataSource()` and `getRemoteDataSource()`. Use **data repository as Single Source of Truth**.
- **Create different models for each layer**, your business rules should NOT be depend on your DB or UI, right? (Ex: only use `AuthCode` as DB entity, create another domain entity for the auth code, and use DataMapper to transport between layers).
- Try applying Clean Architecture base on the current MVVM pattern (the only step you need to do is splitting your business rules into use cases).
- Modularize the project (for easy to maintain & optimize build speed).
- Write **unit-tests**. Remember that "Code without tests is broken as designed".

#### Performance

- Use **single activity** for all screens: use Fragments as screens and **Jetpack Navigation** to navigate between them.
- Use **XML vector drawable** (instead of JPGs/PNGs).
- Avoid creating a `new Handler()` many times.

#### Workflow

- **Your git history is really a mess**. You need to be more careful with your commits. A commit should be meaningful.
- I know this is a "1-man" project, but you also need to **create separate branches** (develop, feature,..) and merge into the master branch using Pull Request.

## Conclusion

Overall your project is good. Hope to see you keep moving up

**Comment by quanguefa23** [comment]
**SOLVED PROBLEM:**
- Don't expose MutableLiveData of your observable fields. Only return LiveData, or the usages can post events and make it harder to control the flow. (Ex: change MutableLiveData<Boolean> getTriggerUpdateTime() to LiveData<Boolean> getTriggerUpdateTime()).  
- Split the SharedPreferences data access into the data repository (instead of access directly in ViewModel). So your ViewModel can be independent of which prefs framework you used.  
- Abstract the login flows behind your own interface, so your ViewModel will not be coupled with GoogleSignIn, and you can change it to other frameworks later.  
- Hide the source of data (remote/local,..) by remove getLocalDataSource() and getRemoteDataSource(). Use data repository as Single Source of Truth.  
- Your git history is really a mess. You need to be more careful with your commits. A commit should be meaningful.
- I know this is a "1-man" project, but you also need to create separate branches (develop, feature,..) and merge into the master branch using Pull Request.
- Avoid creating a new Handler() many times.
- Replace normal Gradle with Kotlin DSL. Split lib versions into a separate file to easy to track & maintain.

**UNSOLVED PROBLEM:**
- Try rewriting the project using Kotlin!
- Create different models for each layer, your business rules should NOT be depend on your DB or UI, right? (Ex: only use AuthCode as DB entity, create another domain entity for the auth code, and use DataMapper to transport between layers).
- Try applying Clean Architecture base on the current MVVM pattern (the only step you need to do is splitting your business rules into use cases).
- Modularize the project (for easy to maintain & optimize build speed).
- Write unit-tests. Remember that "Code without tests is broken as designed".
- Use single activity for all screens: use Fragments as screens and Jetpack Navigation to navigate between them.
- Use XML vector drawable (instead of JPGs/PNGs).

Some suggestion have not been applied yet because it takes a significant amount of time to research and implement. I am going to research and apply them in next weeks.

Thank you very much and highly appreciate for your meticulous review.
